@extends('layouts._heads')
@include('layouts._login_navbar')
@section('body')
    <div class="backgr" xmlns="http://www.w3.org/1999/html">

        <!-- Start The Registration Form -->
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
                    <legend><p>Sign up</p></legend>
                    <form action="{{ url('/register') }}" method="post" class="form" role="form">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-xs-12">
                                <input class="form-control" name="name" placeholder="Full Name" type="text"
                                       required autofocus value="{{ old('name') }}"/>
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <input class="form-control" name="email" placeholder="Email" type="email" required
                                       value="{{ old('email') }}"/>
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <input class="form-control" name="phone" placeholder="Phone Number" type="number"
                                       required value="{{ old('phone') }}"/>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <input class="form-control" name="job_title" placeholder="Job Title:" type="text"
                                       required value="{{ old('job_title') }}"/>
                            </div>

                            <div class="col-xs-12 col-md-6">
                                <input class="form-control" name="city" placeholder="City" type="text" required
                                       value="{{ old('city') }}"/>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <input class="form-control" name="website"
                                       placeholder="Website (If applicable):( optional ) "
                                       type="text" value="{{ old('website') }}"/>
                            </div>


                            <div class="col-xs-12 col-md-12">
                                <textarea class="form-control" name="business"
                                          placeholder="Business & Industry:" required>{{ old('business') }}</textarea>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <textarea class="form-control" name="project_requirement"
                                          placeholder="Your project requirements:( optional )">{{ old('project_requirement') }}</textarea>
                            </div>
                        </div>
                        <input class="form-control" name="password" placeholder="Password" type="password" required/>
                        @if ($errors->has('password'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                        @endif
                        <input class="form-control" name="password_confirmation" placeholder="Confirm Password"
                               type="password" required/>
                        @if ($errors->has('password_confirmation'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                        @endif
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="text-center">
                                        <button type="button" class="forgot-password" data-toggle="modal"
                                                data-target=".bs-example-modal-lg">Terms & Conditions
                                        </button>

                                        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
                                             aria-labelledby="myLargeModalLabel">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content model-content-edit">

                                                    <div class="text-center">  <b>YZTWorks Web Portal – Terms of Use</b></div>
                                                    <br>
                                                    <div class="">  <b> WELCOME TO THE YZTWORKS WEB PORTAL !</b></div>
                                                   <br>
                                                   <br>
                                                    THIS YZTWORKS WEB PORTAL AGREEMENT (“AGREEMENT”) IS A LEGAL AGREEMENT BETWEEN YZTWORKS, INC. (“YZTWORKS”) AND THE PERSON REGISTERING TO ACCESS AND USE THIS PORTAL (“YOU”).  THIS AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR THE USE OF THE YZTWORKS PORTAL AT WWW.YZTWORKS.COM (“PORTAL”) THAT IS OWNED, OPERATED AND MAINTAINED BY YZTWORKS IN ORDER TO PROVIDE CERTAIN SERVICES TO REGISTERED USERS, ALL OTHER SITES OWNED AND OPERATED BY YZTWORKS THAT REDIRECT TO WWW.YZTWORKS.COM, AND ALL SUBDOMAINS AND THE SERVICES PROVIDED THROUGH SUCH PORTAL AND SITES.
                                                    BY SELECTING “I AGREE” YOU ARE YOU ARE DEEMED TO HAVE READ AND ARE INDICATING YOUR ACCEPTANCE OF, AND YOU AGREE TO BE BOUND BY, THE TERMS AND CONDITIONS OF THIS AGREEMENT WHICH SHALL GOVERN YOUR ACCESS AND USE OF THE PORTAL.
                                                    IF YOU DO NOT AGREE WITH ONE OR MORE OF THESE TERMS OF USE YOU MAY NOT ACCESS OR USE THE PORTAL AND MAY EXIT BY CLICKING ON THE “EXIT” BUTTOM BELOW.
                                                    In consideration of the mutual promises and agreements contained in these Terms of Use and other good and valuable consideration (the receipt and sufficiency of which are hereby acknowledged), you and YZTWorks agree as follows:

                                                    <br><br>1. Description of Portal Services. [ The portal is providing digital marketing services and consultation that is based on packages that may include targeted Campaigns in social media, content creation and design that will be targeted to reach potential end customers based on customer service and market] ( “the “Services”).
                                                    <br><br>2. Acceptance of Terms.  The Service is offered subject to acceptance of all of the terms and conditions contained in these Terms of Use, [including the Privacy Policy,] and all other operating rules, policies, and procedures that may be published on the Portal by YZTWorks, which are incorporated by reference and may be updated by YZTWorks without notice to you. Some services offered through the Service may be subject to additional terms and conditions adopted by YZTWorks. Your use of those services is subject to those additional terms and conditions, which are incorporated into these Terms of Use by this reference.
                                                    <br><br>3. Modification of Terms of Use.   YZTWorks reserves the right, at its sole discretion, to modify or replace these Terms of Use, or change, suspend, or discontinue the Service at any time for any reason. YZTWorks may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability. It is your responsibility to check the Terms of Use periodically for changes. Your continued use of the Service following the posting of any changes to the Terms of Use constitutes acceptance of those changes.


                                                    <br><br>4. Registration Data, Accounts and Passwords.<br>
                                                    As part of the process to create, register and maintain your YZTWorks account you must provide YZTWorks with certain current, complete, and accurate registration information, including contact information (including Personal Information) and other data or information that has been requested by YZTWorks during the client account registration or renewal process ("Registration Data"). Registration Data may in certain circumstances include: (i) Other User Registration Data that you provide to YZTWorks; and (ii) credit card or other payment related information in order to pay the Subscription Fee. You agree to maintain and update such Registration Data as necessary in order to keep such information current, complete, and accurate. Registration Data will be used by YZTWorks solely in accordance with the terms of this Agreement.
                                                    You agree to be responsible for: (a) maintaining the confidentiality of any passwords or other account identifiers which you choose or that are assigned to you as a result of any registration with the Portal, and (b) all activities that occur under such password or account. Further, you agree to immediately notify YZTWorks of any unauthorized use of your password or account or in the event that the confidentiality of your password is compromised. YZTWorks shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this Section. Failure to comply with this Section may result in immediate termination of your account. YZTWorks reserves the right, in its sole discretion, to refuse registration of or cancel a user account.
                                                    The Portal Services are not intended to be used by or marketed or directed towards children. To purchase Portal Services you must be at least eighteen (18) years of age and have a valid credit card.
                                                    <br><br>5. Use of the Portal and Content<br><br>

                                                    YZTWorks hereby grants you a limited, non-exclusive, personal, non-transferable and non-sub-licensable and revocable right and license to: (a) access the Portal for the purpose of receiving Portal Services in accordance with the terms of this Agreement; and (b) access, view and print any information and documentation, including the Portal Documentation, made available on the Portal for your personal, non-commercial, and informational use only to assist you in the access and use of the Portal. Use of the Portal is restricted: (i) if you are an individual, to your personal and private use in connection with your use of your Product/service; and (ii) if you represent an entity on who’s behalf you are acting, to the internal and private business use of such entity in connection with the use and management of Product(s) purchased and managed by such entity.
                                                    The portal Content may include certain Third Party Content. You agree that all of the terms and conditions of this Agreement relating to the Portal Services apply to your access to and use of any Third Party Content and you further agree to comply with any terms and conditions that are specific to the Third Party Content and disclosed to you, including the terms and conditions specified in Section 29 of this Agreement.
                                                    All YZTWorks Content is owned solely and exclusively by YZTWorks and/or its third party licensors. You may not: (a) publish, publicly perform or display, or communicate to the public or otherwise distribute to any third party any of the YZTWorks Content; (b) market, sell, re-sell or make commercial use of the Portal or any Content;  (c) systematically collect from the Portal and use any portal Content, including the use of any data mining, robots, or similar data gathering and extraction methods; (d) make derivative uses of the Portal or the Content; (e) reformat or reconfigure or otherwise reverse engineer any portal Content for use on any devices other than Products.
                                                    Except for the limited licenses and rights expressly granted to you, this Agreement does not grant you any other right or license, whether express or implied, by estoppel, or otherwise in or under any patent, trademark, copyright, or other intellectual property or proprietary right of YZTWorks or any third party.
                                                    The Portal Services are subject to any limitations specified in the Portal Documentation or on the Portal from time to time. You agree to comply with all applicable laws in using the Portal Services.
                                                    YZTWorks reserves the right to change, modify, suspend or discontinue the Portal and any or all of the Portal Services at any time for any reason, or for no reason at all, in YZTWorks’ sole discretion, with or without notice to you and YZTWorks may suspend or terminate your access to the Portal immediately without prior notice in YZTWorks’ sole discretion, with or without notice to you and without further obligation or liability to you. YZTWorks shall not have any liability of any kind or any nature whatsoever to you solely by reason of any change, modification, suspension or discontinuance of the Portal or any or all of the Portal Services in accordance with its terms. You agree that you shall not make any claim against YZTWorks, including with respect to any lost revenue, profits or opportunities as a result of such change, modification, suspension or discontinuance or on account of any expenditures made or actions taken in reliance on the expected continuation of the Portal, the Portal Services or this Agreement. Your sole remedy in the event of any such change, modification, suspension or discontinuance shall be the refund of any such portion of pre-paid fees for which you have not received Portal Services.
                                                    This Site contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music and sound, and the entire contents of the Site are protected by copyright as a collective work under Canadian copyright laws. YZTWorks owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. You may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part. You may download, print, and/or save copyrighted material for your personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of YZTWorks or the copyright owner is permitted. If copying, redistribution or publication of copyrighted material is permitted, you will make independent attribution and/or agree to make no changes in or deletion of any author attribution, trademark legend or copyright notice. You acknowledge that you do not acquire any ownership rights by downloading copyrighted material.

                                                    <br><br>6. Rules and Conduct.    As a condition of use, you promise not to use YZTWorks for any purpose that is prohibited by the Terms of Use or law. You are responsible for all of your activity in connection with YZTWorks. You shall not, and shall not permit any third party using your account to, take any action, or submit content, that:
                                                    •    infringes any patent, trademark, trade secret, copyright, right of publicity, or other right of any other person or entity, or violates any law or contract;
                                                    •    you know is false, misleading, or inaccurate;
                                                    •    is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, tortious, obscene, offensive, profane, or invasive of another's privacy;
                                                    •    constitutes unsolicited or unauthorized advertising or promotional material or any junk mail, spam, or chain letters;
                                                    •    contains software viruses or any other computer codes, files, or programs that are designed or intended to interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password, or other information of YZTWorks or any third party; or
                                                    •    impersonates any person or entity, including any employee or representative of YZTWorks.
                                                    You shall not directly or indirectly: (i) decipher, decompile, disassemble, reverse engineer, or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Service, except to the limited extent applicable laws specifically prohibit such restriction; (ii) modify, translate, or otherwise create derivative works of any part of the Service; or (iii) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder. You shall abide by all applicable local, state, national, and international laws and regulations.
                                                    YZTWorks reserves the right to, at any time, for any reason, and without notice: (i) cancel, reject, interrupt, remove, or suspend a campaign or project; (ii) remove, edit, or modify any content, including, but not limited to, any user submission; and (ii) remove or block any user or user submission. YZTWorks reserves the right not to provide reasons for any of these actions.
                                                    Data And Personal Information
                                                    <br> (a)    Registration Data: Registration Data submitted will be used by YZTWorks for the purposes of registering and administering your Portal account and use of Portal Services and to communicate with you. You hereby authorize and provide YZTWorks with the right and authority and consent to use and to disclose to other persons (including any YZTWorks third party service providers and payment processors) Registration Data for the purpose of performing the Portal Services and otherwise as YZTWorks determines is reasonably required in performing its obligations under this Agreement.

                                                    <br>  (b)    Anonymous Transaction Data: YZTWorks retains the right, and to the extent required you hereby authorize and provide YZTWorks with the right and authority, to use any Anonymous Transaction Data for its internal business purposes without limitation or restriction for any purpose YZTWorks may, in its discretion, choose and use and disclose and commercially exploit the Anonymous Transaction Data without limitation or restriction for any purpose YZTWorks may, in its discretion, choose.

                                                    <br> (e)    Personal Information: Except as described in this Agreement or as you may otherwise consent to from time to time or as is provided for in YZTWorks’ Privacy Policy. YZTWorks will not use, and will not disclose or provide any of Personal Information included in Registration Data to any other person.  Subject to the terms of this Agreement, Registration Data shall be collected, used and maintained by YZTWorks in accordance with YZTWorks’ Privacy Policy. Click here to review YZTWorks Privacy Policy.

                                                    You represent and warrant to YZTWorks that you have the full, unrestricted right and authority and have been fully authorized to provide to YZTWorks any and all Registration Data (including any Personal Information and Other User Registration Data) for the purposes of this Agreement and that YZTWorks is authorized and permitted to use such data as and to the extent provided in this Agreement.  You agree that YZTWorks has the right to monitor and review your use of the Portal Services from time to time and you agree that YZTWorks may in its discretion preserve and may disclose without liability to you any data concerning you where required to do so by law (including if ordered to do so by a court having jurisdiction over YZTWorks) or where such disclosure is reasonably believed by YZTWorks to be necessary to ensure compliance with applicable law or to enforce this Agreement or protect the rights and interests of YZTWorks or any other person. YZTWorks will use reasonable efforts to protect any Registration Data that you upload to the Portal or otherwise provide to YZTWorks.  Once such data has been received or generated by YZTWorks, YZTWorks employs physical, administrative and technical safeguards, reasonably appropriate to the sensitivity of the information, to safeguard your such data (including any Personal information therein) against loss, theft, misuse, unauthorized access or disclosure. Unfortunately, no data transmission over the Internet or system can be guaranteed to be 100% secure.  Although YZTWorks uses reasonable efforts to safeguard your data and information, YZTWorks cannot guarantee it.  YZTWorks cannot ensure or guarantee that any data or information you provide or transmit to YZTWorks or that YZTWorks transmits to you is completely secure from individuals who might attempt to deliberately evade security measures, including by intercepting wireless transmissions or transmissions over the Internet. You provide YZTWorks with your data and information and authorize YZTWorks to report to you at your own risk.

                                                    <br><br>10.    Subscription Fees and Charges<br>

                                                    Your use of the Portal Services shall be subject to current subscription charges (“Subscription Fee”) for the Portal Services applicable to the Term you have selected which are disclosed to you during your initial registration or any subsequent Term renewal process, plus all applicable taxes.  The Subscription Fee is payable in Canadian currency in advance by credit  or debit card prior to being made available to you. You hereby agree to pay all Subscription Fees to your account, plus all applicable taxes. YZTWorks reserves the right to terminate or suspend the Portal Services at any time in the event of any non-payment by you.  Subscription Fees are non-refundable except where required under applicable law.

                                                    <br><br> 11.    Portal Documentation<br>
                                                    You may make a reasonable number of copies of the Portal Documentation to the extent reasonably required for your use of the Portal Services or Product; provided that you shall cause to be reproduced, marked on or included in such copies of the Portal Documentation made, such copyright, trade-mark and other proprietary and confidentiality notices as existed on the original indicating that the Portal and related Products and services is the intellectual property of YZTWorks and/or its licensors as the case may be.
                                                    <br><br>12.    Ownership<br>
                                                    Save and except for the limited rights and licenses explicitly granted or contemplated by the Agreement, all right, title and interest (including all intellectual property and other proprietary rights and interests) in and to the Portal and all technology, software, content, information, data, documentation and materials forming part of or contained on or available through or from the Portal is the sole and exclusive property of YZTWorks or its licensors. Nothing in the Agreement shall, or shall be deemed or construed to, assign, transfer or convey to you any title, rights or interest in or to any technology, data, information, content, documentation or intellectual property other than the licenses specifically and expressly granted herein.
                                                    <br><br> 13.    Portal Use Restrictions
                                                    You agree that when using the Portal you will not: (a) post or transmit any files which contain viruses, worms, Trojan horses or other code that manifests contaminating or destructive properties; (b) post or transmit data or content which violates or infringes any third party rights or is injurious to a third party or defames, libels or disparages any third party; (c) except as expressly permitted by the Agreement, provide, disclose, sublicense, distribute, transfer, assign or otherwise permit any third party to access, use, read or otherwise gain access to the Portal; (d) use or attempt to use the Portal or Portal Services in conjunction with any product or device other than the Product; (e) use the Portal to act as a “service bureau” to provide the benefit of the use of the Portal Services to or for any other person (provided that the foregoing restriction shall not be construed to prohibit the use of the Portal as permitted hereunder in the management of multiple Products; I(f) to the maximum extent permitted to be restricted by applicable law interfere with or circumvent any copyright or other technical protection mechanism or reverse engineer, decompile, disassemble, or otherwise in any manner deconstruct all or any part of the Portal or any software or technology or content forming part thereof; or (g) post or transmit data or content which would be considered a criminal offence, give rise to civil liability, or would otherwise violate the law. You may not use any spider, robot or other automated or electronic agent to monitor or copy web pages or any content from the Portal or for any other purpose in connection with your access to and use of the Portal.  You shall not take any action or use any program or device that may result in or is intended to interfere with the operation and functioning of the Portal or to shut down, overload or overwhelm the Portal.
                                                    <br><br> 14.    Support<br>
                                                    YZTWorks may in its discretion, without any obligation to do so and subject to the limitations of this Agreement (or as may be included in the Portal Documentation or posted on the Portal from time to time), provide you with the troubleshooting support concerning your use of the Portal and Portal Services.
                                                    <br><br>15.    Portal and Portal Services Provided “AS IS”
                                                    YOU EXPRESSLY UNDERSTAND AND AGREE THAT THE PORTAL, THE PORTAL SERVICES, ANY CONTENT AND OTHER INFORMATION, DATA AND MATERIALS AVAILABLE ON THE PORTAL OR AS PROVIDED AS PART OF THE PORTAL SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT, AND EXCEPT TO THE EXTENT EXPRESSLY PROVIDED FOR HEREIN YZTWORKS EXPRESSLY DISCLAIMS ALL REPRESENTATIONS OR WARRANTIES OR CONDITIONS OF ANY KIND OR NATURE WHATSOEVER, WHETHER EXPRESS OR IMPLIED, AND WHETHER ARISING BY STATUTE OR OTHERWISE IN LAW, FROM A COURSE OF DEALING OR USAGE OF TRADE, AND  INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OR CONDITIONS, ANY CONDITION OR WARRANTY OF MERCHANTABILITY, TITLE OR NON-INFRINGEMENT OF THIRD PARTIES RIGHTS AND ANY CONDITION OR WARRANTY OF FITNESS FOR PARTICULAR PURPOSE.
                                                    YZTWORKS DOES NOT OFFER ADVICE OR RECOMMENDATIONS CONCERNING INFORMATION OR DATA CONTAINED IN ANY CONTENT AND ANY ACTIONS TAKEN, OR FAILURES TO ACT, IN RELIANCE ON ANY CONTENT (OR OTHERWISE ON THE PORTAL SERVICES) BY YOU OR ANY OTHER PERSON IS YOUR SOLE RESPONSIBILITY AND LIABILITY.  YZTWorks SPECIFICALLY MAKES NO REPRESENTATIONS OR WARRANTIES THAT THE PORTAL OR ANY OF THE PORTAL SERVICES  (INCLUDING THE PROVISION OF ANY CONTENT) WILL BE ACCURRATE, RELIABLE OR COMPLETE OR WILL BE PROVIDED ON AN UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE BASIS OR THAT ANY ERRORS CAN OR WILL BE CORRECTED OR THAT ANY PORTAL SERVICES, CONTENT, DATA OR THE RESULTS DERIVED THEREFROM WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS OR THAT THE PORTAL AND ITS SERVER ARE FREE OF COMPUTER VIRUSES AND OTHER HARMFUL ELEMENTS.
                                                    YZTWorks IS NOT RESPONSIBLE FOR ERRORS OR DELAYS OR FAILURES IN TRANSMISSION OVER THE INTERNET OR ANY WIRELESS NETWORK OR ERRORS OR DELAYS OR RESULTS CAUSED BY OR ATTRIBUTABLE TO THE USE OF OR RELIANCE ON ANY THIRD PARTY SMARTPHONE OR SIMILAR DEVICE OR TECHNOLOGY.  SOME JURISDICTIONS DO NOT PERMIT LIMITATIONS ON OR EXCLUSIONS OF CERTAIN IMPLIED WARRANTIES, OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES; THEREFORE THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU IN CERTAIN CIRCUMSTANCES.
                                                    YZTWORKS MAKES NO GUARANTEE OF CONFIDENTIALITY OR PRIVACY OF ANY COMMUNICATION OR INFORMATION TRANSMITTED ON THE SITE OR ANY WEBSITE LINKED TO THE SITE. YZTWorks will not be liable for the privacy of email addresses, registration and identification information, disk space, communications, confidential or trade-secret information, or any other Content stored on YZTWorks’s equipment, transmitted over networks accessed by the Site, or otherwise connected with your use of the Service.
                                                    YZTWorks has no special relationship with or fiduciary duty to you. You acknowledge that YZTWorks has no duty to take any action regarding any of the following: which users gain access to the Site; what content users access through the Site; what effects the content may have on users; how users may interpret or use the content; or what actions users may take as a result of having been exposed to the content. YZTWorks cannot guarantee the authenticity of any data or information that users provide about themselves or their campaigns and projects. You release YZTWorks from all liability for your having acquired or not acquired content through the Site. The Site may contain, or direct you to websites containing, information that some people may find offensive or inappropriate. YZTWorks makes no representations concerning any content on the Site, and YZTWorks is not liable for the accuracy, copyright compliance, legality, or decency of material contained on the Service.
                                                    IF YOU ARE DISSATISFIED WITH THE PORTAL, THE PORTAL SERVICES OR WITH ANY OF THE TERMS, CONDITIONS, GUIDELINES, PRACTICES OR POLICIES OF YZTWORKS IN OPERATING THE PORTAL AND IN PROVIDING THE PORTAL SERVICES YOU AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY SHALL BE TO DISCONTINUE USING THE PORTAL AND PORTAL SERVICES.
                                                    <br><br>16.    Limitation<br>
                                                    UNDER NO CIRCUMSTANCES SHALL YZTWorks, ITS  DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, AFFILIATES, AGENTS AND THIRD-PARTY CONTRACTORS, SUPPLIERS AND LICENSORS (COLLECTIVELY THE "YZTWorks PARTIES") BE LIABLE TO YOU OR TO ANY OTHER PARTY FOR ANY LOSS OR DAMAGE OF ANY KIND OR NATURE WHATSOEVER THAT IS SUFFERED OR INCURRED IN ANY CONNECTION WITH THE USE OF (OR THE INABILITY TO USE) THE PORTAL OR THE PROVISION OF THE PORTAL SERVICES  (REGARDLESS OF THE FORM OF ACTION OR THEORY OF LIABILITY, INCLUDING FOR BREACH OF CONTRACT, TORT, NEGLIGENCE, EQUITY, STRICT LIABILITY, BY STATUTE OR OTHERWISE AND REGARDLESS OF THE OCCURANCE OF A FUNDAMENTAL BREACH OR FAILURE OF ESSENTIAL PURPOSE) THAT EXCEEDS, IN THE AGGREGATE, THE AMOUNTS THAT YOU HAVE PAID YZTWorks IN RESPECT OF THE PORTAL SERVICES IN THE THIRTY (30) DAY PERIOD THAT IMMEDIATELY PRECEEDED THE DATE OF YOUR CLAIM.
                                                    IN NO EVENT WHATSOEVER SHALL ANY OF THE YZTWorks PARTIES BE LIABLE FOR ANY SPECIAL, EXEMPLARY, PUNITIVE, CONSEQUENTIAL, INCIDENTAL OR INDIRECT DAMAGES OF ANY KIND OR NATURE WHATSOEVER THAT IS SUFFERED OR INCURRED IN ANY CONNECTION WITH THE USE OF PORTAL OR THE PROVISION OF THE PORTAL SERVICES (INCLUDING IN ANY CONNECTION WITH THE TRANSMISSION OR DOWNLOADING OR STORAGE OF ANY DATA OR SUBMISSIONS TO OR FROM THE PORTAL OR THE USE OF, OR RELIANCE ON, ANY CONTENT OR OTHER INFORMATION OR DATA CONTAINED ON OR PROVIDED THROUGH THE PORTAL OR PORTAL SERVICES, OR LOSS OF OR DAMAGE TO FILES OR DATA OR ANY COSTS OF RECOVERING OR REPRODUCING ANY FILES OR DATA OR LOSS OF USE OR LACK OF AVAILABILITY OF SERVICES OR ANY BUSINESS INTERRUPTION OR LOSS OF REVENUE OR PROFIT OR ANY OTHER ECONOMIC LOSS WHATSOEVER) HOWEVER CAUSED AND REGARDLESS OF THE FORM OR CAUSE OF ACTION AND WHETHER OR NOT FORESEEABLE, EVEN IF THE YZTWorks PARTIES OR ANY OF THEM HAS BEEN INFORMED IN ADVANCE OR OUGHT REASONABLY TO HAVE KNOWN OF THE POTENTIAL FOR SUCH DAMAGES.
                                                    THE ENTIRE RISK AS TO THE RESULTS AND PERFORMANCE AND USE OF THE PORTAL, PORTAL SERVICES, PRODUCT, SOFTWARE AND ANY PROVIDED SUPPORT IS ASSUMED BY YOU.
                                                    Indemnity
                                                    You agree to defend, indemnify, and hold harmless the YZTWorks Parties from and against any claims, actions, demands, losses, liabilities, damages, costs and expenses suffered by such persons, including without limitation, reasonable legal and accounting fees, alleging or resulting, directly or indirectly, from or in any connection with your (or any user of your account's): (a) breach of this Agreement; (b) access to the Portal or use of the Portal Services; and (c) uploading to or other provision of or disclosure to YZTWorks of any Registration Data or any other information or data and the use of same by YZTWorks or other YZTWorks Party as contemplated hereunder. YZTWorks shall provide notice to you of any such claim or losses and shall reasonably assist you, at your expense, in defending any such claim.
                                                    Trade-marks
                                                    All product, brand and company names and logos and trade-marks displayed on the Portal or used in connection with the Portal Services are the trade-marks of YZTWorks (or its suppliers or third party licensors). Any use of any of the marks appearing on the Portal or in connection with the Portal Services without the express written consent of YZTWorks or the owner of the mark, as appropriate, is strictly prohibited.
                                                    Links
                                                    YZTWorks may from time to time include links on this Portal to other portals or web sites or resources, including those operated by parties other than YZTWorks. These links are provided for your convenience and YZTWorks is not responsible for the availability of such portals, web sites or resources and does not endorse or accept responsibility for the content of such external portals, web sites or resources and has no responsibility for or control over the privacy policy (if any) of the operators of the external websites. Your access and viewing of any third party sites is conducted at your own risk. You are strongly advised to check the terms and conditions of use and the privacy policies of these external portals or web sites before entering or making use of them.  No "deep links" into the Portal are permitted. By linking (to the extent permitted), you agree that YZTWorks may require the link to be removed if, in YZTWorks’ sole opinion, any aspect of the linking portal or website, its content or any other matter relating to the link is objectionable to YZTWorks.

                                                    No Framing, etc.
                                                    Any copying, republication or redistribution of any part of the Portal, including by caching, framing or similar means, is expressly prohibited without the prior written consent of YZTWorks.
                                                    <br><br>21.    English Language<br>
                                                    The parties declare that they have required that this Agreement and all documents related hereto, either present or future, be drawn up in the English language only. Les parties déclarent par les présentes qu'elles exigent que cette entente et tous les documents y afférents, soit pour le présent ou le futur, soient rédigés en langue anglaise seulement.
                                                    <br><br>22.    General Provisions<br>
                                                    No delay or omission by YZTWorks to exercise any right or power it has under this Agreement or to object to the failure of any covenant of you to be performed in a timely and complete manner, shall impair any such right or power or be construed as a waiver of any succeeding breach or any other covenant.  Any waivers by YZTWorks must be in writing and signed by an authorized representative of YZTWorks. The Agreement constitutes the entire agreement between the parties as it relates to the access to and use of the Portal and Portal Services and the subject matter of this Agreement and supersedes all prior or contemporaneous agreements, negotiations, representations and proposals, written or oral between YZTWorks and you. The Agreement may only be amended or supplemented by written agreement executed by each of the parties. In this Agreement: (a) words denoting the singular include the plural and vice versa and words denoting any gender include all genders; (b) all usage of the word “including” or the phrase “e.g.,” shall mean “including, without limitation,” throughout the Agreement; (c) all dollar amounts are expressed in Canadian currency unless expressly provided otherwise; (d) the division of the Agreement into separate Sections, Subsections and the insertion of headings is for convenience of reference only and shall not affect the construction or interpretation of the Agreement; (e) words or abbreviations which have well-known or trade meanings are used herein in accordance with their recognized meanings; and (f) the parties agree that the Agreement shall not be construed in favor of or against any party by reason of the extent to which any party or its professional advisors participated in the preparation of the Agreement. YZTWorks shall not be liable or responsible for any failures or delays in performing caused by acts or event or circumstances beyond its control. The terms and conditions of this Agreement that limit liability reflect an informed voluntary allocation of risk; such allocation represents a material part of this Agreement. Each party agrees that the limitations of liabilities set out in this Agreement are fair and reasonable in the circumstances. Nothing in this Agreement will deprive you of the benefits of any applicable consumer protection laws, except to the extent lawfully waived by the terms hereof.
                                                    <br><br>23.    Severability / Electronic Documents
                                                    If any provision of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable in any respect, then the remaining provisions of this Agreement, or the application of such provisions to persons or circumstances other than those as to which it is invalid or unenforceable shall not be affected thereby, and each such provision of this Agreement shall be valid and enforceable to the extent granted by law.  This electronic document, and all other electronic documents referred to or incorporated herein, will be: (a) deemed for all purposes to be a "writing" or "in writing," and to comply with all statutory, contractual, and other legal requirements for a writing; and (b) legally enforceable as a signed writing as against the parties subject to the electronic documents. A printed version of the Agreement and any notice given in electronic form shall be admissible in judicial proceedings or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
                                                    <br><br>25.    Conformance with Law<br>
                                                    In addition to complying with this Agreement, you agree to use the Portal and Portal Services for lawful purposes only and in a manner consistent with all applicable local, national or international laws and regulations, including all privacy and personal information laws. The Portal and any Portal Services shall not be used where, and to any extent, such use is prohibited by law. Your use of the Portal from any location is subject to your compliance with all applicable laws and regulations that may be applicable to you. You agree, and confirm, that your use of the Portal is in full compliance with the laws of the jurisdiction(s) to which you are subject, and that you are not prohibited from using the Portal due to any restriction whatsoever and that you have obtained all necessary consents and approvals required or reasonably necessary.
                                                    <br><br>25.        Agreement Not Transferable<br>
                                                    This Agreement shall be binding upon and shall ensure to the benefit of and be enforceable by each of the parties, their respective successors and permitted assigns. You may not assign all or any part of this Agreement. If you are a business or other entity and have undertaken a reorganization such that you wish that an affiliate be responsible to manage iLane Products purchased by you or if you sell all or substantially all of your assets to another person or you are acquired by or merge with another person (in each case such other person a “Transferee”) YZTWorks shall permit such Transferee to register on the Portal to receive Portal Services in respect of such iLane Products/services originally purchased by you, provided that: (a) you provide prior written notice to YZTWorks; (b) the Transferee registers on the Portal and agrees to the current form of Agreement with YZTWorks; (c) your  rights hereunder shall terminate effective upon such registration (and you may not re-register). If you grant a security interest in your assets and undertakings the secured party shall have no rights to use the Portal or transfer this Agreement. YZTWorks may assign this Agreement without your consent at any time.
                                                    <br><br>26.    Changes To Terms And Conditions<br>
                                                    YZTWorks may revise the Agreement at any time by providing you with notice that the Agreement has been amended by email at the address you provided as part of your Registration Data and provide you with the opportunity to review the amended Agreement and require that you accept the amended Agreement prior to being permitted to continue to access and use the Portal and Portal Services. Your agreement to the amended Agreement shall become effective at the time you indicate your agreement to YZTWorks.
                                                    <br><br>27.    Termination<br>
                                                    YZTWorks may terminate this Agreement if you fail to comply with any provision of this Agreement. The disclaimers, limitations on liability, termination, interpretative provisions, your warranties and indemnities shall survive any termination of this Agreement. YZTWorks shall not be required to refund to you any amounts prepaid for use of any Portal Services if YZTWorks has terminated your account or your use of, or access to, the Portal and/or any of the Portal Services for breach of this Agreement.
                                                    <br><br>28.    Contact / Notices<br>
                                                    All notices and communications by or to a party shall be in writing and shall be deemed to have been duly given when made (a) via e-mail to ■info@yztworks.com■.■ for notices to YZTWorks, or to the e-mail address that you provided to YZTWorks as part of the Registration Data for notices to you or (b) delivered in person, by courier or deposited in the mail, postage prepaid, certified mail, return receipt requested, and addressed to you at the address that you provided to YZTWorks as part of the Registration Data for notices to you and addressed to Intelligent Mechatronic SystemsYZTWorks Inc., 161 Roger Street, Waterloo,91 McLennan Way, Kanata Ontario  Canada N2J 1B1295K2L 2T3, attention Chief Financial OfficerDirector. Either party may revise its contact information by sending the other the corrected information as specified in the preceding sentence. YZTWorks may also broadcast notices or messages, or other matters of importance, on the Portal; and you agree that such broadcasts shall constitute notice to you whether or not you actually access the communication or notice via the Portal.  Notice by e-mail or posting on the Portal shall be deemed given forty-eight (48) hours after the e-mail is sent or is posted, unless in the case of e-mail  the sending party is notified that the e-mail address is invalid. YZTWorks full contact information (including telephone number) for general inquiries is set forth on the Portal.
                                                    <br><br>29.    Third Party Terms and Notices<br>
                                                    [NTD: Client to advise whether any third party terms or notices should be included herein, Third party is Facebook, twitter, instgram, pintrest, google +, youtube,.. social media platforms.]
                                                    <br>
                                                    Collection of Personal Information.  Information posted on YZTWorks is publicly available. YZTWorks’s servers are located in Canada and elsewhere in the world where YZTWorks has facilities. Therefore, if you choose to provide YZTWorks with personal information, you are consenting to YZTWorks’s collection, use, disclosure of your personal information and to the transfer and storage of that information on our servers in Canada and elsewhere in the world where YZTWorks has facilities. In addition to the information you voluntarily provide or enter or store on the Site, YZTWorks collects and stores the following personal information:
                                                    <br>•    computer sign-on data, statistics on page views, traffic to and from YZTWorks and ad data; and
                                                    <br>•    other information, including users IP address and standard web log information.
                                                    Disclosure.  YZTWorks may sell or rent users' personal information to third parties for their marketing purposes without users’ explicit consent. YZTWorks may disclose personal information to respond to legal requirements, enforce our policies, respond to claims that a posting or other content violates other's rights, or protect anyone's rights, property, or safety. YZTWorks may also share personal information with:
                                                    <br>•    corporate affiliates;
                                                    <br>•    service providers;
                                                    <br>•    third-party websites and publishers;
                                                    <br>•    YZTWorks merchants who require information on the YZTWorks customers who purchased their offer so that the offer can be fulfilled.
                                                    Communications and email tools.  You agree to receive marketing communications from YZTWorks unless you indicate that you prefer not to receive such communications. You may not use our site or communication tools to harvest addresses, send spam or otherwise breach our Terms of Use or Privacy Policy. YZTWorks may automatically scan, manually filter messages sent via our communication tools for malicious activity or prohibited content. YZTWorks may permanently store such messages sent via our communication tools. YZTWorks reserves the right to delay replies in cases of suspected fraudulent activity or violations of the YZTWorks Terms of Use and/or to refuse to transmit messages. If you use our tools to send content to a friend, YZTWorks may permanently store your friends' addresses or use or disclose them for marketing purposes.
                                                    Access, Modification, and Deletion.   You can see, modify or erase most of your personal information by reviewing and modifying your posting or account status page, or by contacting customer support to review any personal information YZTWorks stores that is not available on the Site. There may be a charge associated with such requests but these will not exceed the amounts permitted by law.
                                                    Security.  YZTWorks takes measures to protect your personal information against unauthorized access and disclosure, but YZTWorks makes no guarantees as to the security of your personal information or any other information you provide to YZTWorks.
                                                    Cookies.  YZTWorks or its service providers may use "cookies" on some parts of the Site to help analyze our web page flow; customize our services, content and advertising; measure promotional effectiveness, and promote trust and safety. YZTWorks also may work with service providers who may place cookies on your computer to serve and measure the effectiveness of ads on our or our advertising partners' behalf and collect information about how you use websites owned by YZTWorks and its affiliates. This information allows them to help us customize our content and advertising. YZTWorks does not allow these companies to collect any personal information about you using these cookies.
                                                    YZTWorks Classifieds Posting Policy.   Generally, you may not list, buy or sell items or services that are illegal to own, buy or sell in your province of residence, or that are not bought or sold in compliance with applicable laws and regulations. You are responsible for ensuring compliance with all applicable laws relating to the item you list, buy or sell. In addition, the following specific activities are prohibited from YZTWorks:
                                                    <br>•    Posting an Ad if you are not located in Canada
                                                    <br>•    Posting an item for sale that is not located in Canada
                                                    <br>•    Posting an item for sale that is illegal to own, buy or sell in your area of residence
                                                    <br>•    Posting an item for sale that is in the prohibited items and services list
                                                    <br>•    Posting duplicate Ads in multiple categories or multiple cities
                                                    <br>•    Posting Ads using multiple different email addresses
                                                    <br>•    Posting an Ad that serves no other purpose other than to send traffic to a web site
                                                    <br>•    Posting a multi-level marketing or other prohibited job
                                                    <br>•    Posting an Ad that contains adult, mature or erotic content. Personals are not allowed.
                                                    <br>•    Posting an Ad that defames anyone or contains "hate speech"
                                                    <br>•    Posting opinions, notices, and discussion topics not in the discussion forums
                                                    <br>•    Posting deliberately misleading information
                                                    Any Ads that do not comply with the Classifieds Posting Policy will be removed from the site. Additionally, users that violate such policies may be blocked from using YZTWorks in the future.
                                                    YZTWorks My Deals.  Vouchers you purchase through our Site as a YZTWorks account holder are special promotional offers that you purchase from participating merchants through our service. The vouchers are redeemable for certain goods, services or experiences offered by, or facilitated through, the Merchant identified on the voucher. The Merchant is solely responsible for redeeming the voucher. The Merchant is the issuer of the voucher and is fully responsible for all goods and services it provides to you and for any and all injuries, illnesses, damages, claims, liabilities and costs (“Liabilities”) it may cause you to suffer, directly or indirectly, in full or in part, whether related to the use or redemption of a voucher or not. You waive and release YZTWorks and its subsidiaries, affiliates, partners, officers, directors, employees and agents from any Liabilities arising from or related to any act or omission of a Merchant in connection with your use of a voucher or the services/goods it provides in connection with it.
                                                    By purchasing any voucher you agree to the terms of this Agreement and these Terms of Sale. By purchasing, viewing a mobile version, printing, accepting, using or attempting to use any voucher, you agree to these Terms of Sale specifically (“rules”) the terms on the voucher itself and any additional, deal specific terms advertising the voucher at the time of purchase. These rules apply to all promotional vouchers that we make available, unless a particular voucher states otherwise, and except as otherwise required by law. In the event of a conflict between these rules and a voucher’s fine print, the voucher’s fine print will control.
                                                    Intellectual Property of Users.  By submitting any information to the Site, you agree to the following terms:
                                                    <br>•    YZTWorks needs a license to perform and market the Service. You grant to YZTWorks the worldwide, non-exclusive, perpetual, irrevocable, royalty-free, sublicensable, transferable right to (and to allow others acting on its behalf to) (i) use, edit, modify, prepare derivative works of, reproduce, host, display, stream, transmit, playback, transcode, copy, feature, market, sell, distribute, and otherwise fully exploit your User Submissions and your trademarks, service marks, slogans, logos, and similar proprietary rights (collectively, the "Trademarks") in connection with (a) the Service, (b) YZTWorks’s (and its successors' and assigns’) businesses, (c) promoting, marketing, and redistributing part or all of the Site (and derivative works thereof) or the Service in any media formats and through any media channels (including, without limitation, third-party websites); (ii) take whatever other action is required to perform and market the Service; (iii) allow its Users to stream, transmit, playback, download, display, feature, distribute, collect, and otherwise use the User Submissions and Trademarks in connection with the Service; and (iv) use and publish, and permit others to use and publish, the user submissions, Trademarks, names, likenesses, and personal and biographical materials of you and the members of your group, in connection with the provision or marketing of the Service. The foregoing license grant to YZTWorks does not affect your other ownership or license rights in your user submissions, including the right to grant additional licenses to your submissions.
                                                    <br>•    You grant to each user a non-exclusive license to access your submissions through the Service, and to use, edit, modify, reproduce, distribute, prepare derivative works of, display and perform such submissions solely for personal, non-commercial use.
                                                    <br>•    You further agree that your user submissions will not contain third-party copyrighted material, or material that is subject to other third-party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant YZTWorks all of the license rights granted herein.
                                                    <br>•    You will pay all royalties and other amounts owed to any person or entity based on your submitting user submissions to the Service or YZTWorks’s publishing or hosting of the user submissions as contemplated by these Terms of Use.
                                                    <br>•    The use or other exploitation of user submissions by YZTWorks and its users as contemplated by this Agreement will not infringe or violate the rights of any third party, including without limitation any privacy rights, publicity rights, copyrights, contract rights, or any other intellectual property or proprietary rights.
                                                    <br>•    YZTWorks shall have the right to delete, edit, modify, reformat, excerpt, or translate any of your user submissions.
                                                    <br>•    All information publicly posted or privately transmitted through the Site is the sole responsibility of the person from which that content originated.
                                                    <br>•    YZTWorks will not be liable for any errors or omissions in any Content.
                                                    <br>•    YZTWorks cannot guarantee the identity of any other users with whom you may interact while using the Service.
                                                    <br>•    All content you access through the Service is at your own risk and you will be solely responsible for any resulting damage or loss to any party.
                                                    International. Accessing the Service is prohibited from territories where the content is illegal. If you access the Service from other locations, you do so at your own initiative and are responsible for compliance with local laws.
                                                    Electronic Delivery, Notice Policy, and Your Consent. By using the Services, you consent to receive from YZTWorks all communications including notices, agreements, legally required disclosures, or other information in connection with the Services (collectively, "Contract Notices") electronically. YZTWorks may provide the electronic Contract Notices by posting them on the Site.
                                                    Governing Law.  YZTWorks controls the Site from its offices within the Province of Ontario, Canada. The Site can be accessed from all provinces and territories of Canada and from other countries around the world. As each of these jurisdictions have laws that may differ from those of the Province of Ontario, by accessing the Site, you agree that all matters relating to access to, or use of, the Site, or any other hyperlinked website, shall be governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein. You also agree and hereby submit to the non-exclusive personal jurisdiction and venue of the courts of the Province of Ontario and acknowledge that you do so voluntarily and are responsible for complying with all local laws. You hereby irrevocably waive any right you may have to trial by jury in any dispute, action, or proceeding.
                                                    Integration and Severability.   These Terms of Use and other referenced material are the entire agreement between you and YZTWorks with respect to the Service, and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and YZTWorks with respect to the Service and govern the future relationship. If any provision of the Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms of Use will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.
                                                    Miscellaneous.   YZTWorks shall not be liable for any failure to perform its obligations hereunder where the failure results from any cause beyond YZTWorks’s reasonable control, including, without limitation, mechanical, electronic, or communications failure or degradation. The Terms of Use are personal to you, and are not assignable, transferable, or sublicensable by you except with YZTWorks’s prior written consent. YZTWorks may assign, transfer, or delegate any of its rights and obligations hereunder without consent. No agency, partnership, joint venture, or employment relationship is created as a result of the Terms of Use and neither party has any authority of any kind to bind the other in any respect. In any action or proceeding to enforce rights under the Terms of Use, the prevailing party will be entitled to recover costs and attorneys' fees. All notices under the Terms of Use will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; or the day after it is sent, if sent for next day delivery by recognized overnight delivery service.



                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <button class="form-control btn btn-register " type="submit">
                            Sign up
                        </button>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="text-center">
                                        <a href="{{ url('/login') }}" class="forgot-password">already have an
                                            account</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
